ALTER TABLE "DailyEntry" ADD COLUMN "sabaqSaved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DailyEntry" ADD COLUMN "sabaqParaSaved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DailyEntry" ADD COLUMN "manzilSaved" BOOLEAN NOT NULL DEFAULT false;
